[[plugins]]
repo = 'kannokanno/previm'
on_ft = ['markdown']

[[plugins]]
repo = 'tyru/open-browser.vim'
on_ft = ['markdown']

[[plugins]]
repo = 'Shougo/echodoc.vim'
on_source = ['LanguageClient-neovim']
hook_add = '''
set cmdheight=2
let g:echodoc#enable_at_startup = 1
let g:echodoc#type = 'signature'
set signcolumn=yes
'''

[[plugins]]
repo = 'majutsushi/tagbar'
on_ft = ['cpp', 'c']
hook_add = '''
nmap <F8> :TagbarToggle<CR>
let g:tagbar_width = 30
'''

[[plugins]]
repo = 'soramugi/auto-ctags.vim'
on_source = ['tagbar']
hook_add = '''
let g:auto_ctags = 1
let g:auto_ctags_directory_list = ['.git']
let g:auto_ctags_tags_args = '--tag-relative --recurse --sort=yes'
set tags+=.git/tags
'''
